services:
  # Servicio de base de datos PostgreSQL
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
      
  # Servicio de API principal (FastAPI)
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network

  # Redis para gestión de WebSockets, caché y broker de Celery
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # Celery worker para procesar tareas en segundo plano
  celery-worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    restart: always
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
    networks:
      - app-network

  # Celery beat para tareas programadas
  celery-beat:
    build:
      context: .
      dockerfile: ./docker/beat/Dockerfile
    restart: always
    volumes:
      - ./backend:/app
      - celery_beat_data:/app/celerybeat
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
      - celery-worker
    networks:
      - app-network

  # Flower para monitoreo de Celery (versión simplificada que no depende de la configuración completa)
  flower:
    image: mher/flower:0.9.7
    restart: always
    ports:
      - "5555:5555"
    command: ["flower", "--broker=redis://redis:6379/0", "--port=5555"]
    depends_on:
      - redis
      - celery-worker
    networks:
      - app-network

  # Nginx para servir archivos estáticos y proxy inverso
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  celery_beat_data:

networks:
  app-network:
    driver: bridge